# Generated by Django 5.2.10 on 2026-02-08 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskplanner', '0004_plantask'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_start', models.DateTimeField()),
                ('suggested_end', models.DateTimeField()),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskplanner.plantask')),
            ],
        ),
    ]
