# Generated by Django 5.2.10 on 2026-02-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskplanner', '0005_plansuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
