# Generated by Django 5.2.10 on 2026-02-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskplanner', '0006_alter_plantask_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantask',
            name='desired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
