# Generated by Django 5.2.10 on 2026-02-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskplanner', '0007_plantask_desired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansuggestion',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
